layout_spectrum: 1
typography_spectrum: 0.5268528
color:
  saturation: 0.2075438
  lightness: 0.3474646
  brandStrength: 0.9430271
  rhythmicContrast: 0.8627754
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: MUSSICA LIVE
